server:
  port: 9090
  
  
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



  cloud:
    stream:
      bindings:
        iotmessageChannel.destination: deviceMessages
        
logging:
  level:
    org.springframework.web: ERROR
    com.asiczen: TRACE
  file:
    name: /home/lora/webApplications/app-logs/mqtt-subscriber.log
    max-size: 10 MB        